# see https://pre-commit.com
# HOWTO: https://www.youtube.com/watch?v=psjz6rwzMdk
# for making it run: "pre-commit install"

# specify 
# - git repo (here https://github.com/psf/black)
# - tag (here 21.9b0)
# - which commeand to run (here black)
# # further options (here --safe)
repos:
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
        args: [--safe]

-   repo: https://github.com/asottile/reorder_python_imports
    rev: v3.9.0
    hooks:
    -   id: reorder-python-imports