[tool.poetry]
name = "TAInstCalorimetry"
version = "0.1.9"
description = "Handling TAM Air calorimetry files made easy."
authors = [
    "mj-hofmann <aCodingChemist@gmail.com>",
    "tgaedt <torben.gaedt@tum.de>"
]
license = "GNU GENERAL PUBLIC LICENSE"

repository = "https://github.com/mj-hofmann/TAInstCalorimetry"

# README file(s) are used as the package description
readme = "README.md"

# Keywords (translated to tags on the package index)
keywords = ["calorimetry", "TAM Air", "TA Instruments", "analysis", "vizualisation"]

[tool.poetry.dependencies]
python = ">=3.7,<3.12"
requests = "^2.28.1"
xlrd = "^2.0.1"
pytest = "^7.2.0"
pytest-cov = "^4.0.0"
mypy = "^0.991"
pysnooper = "^1.1.1"
matplotlib = "^3.6.3"
pandas = "^1.5.3"
scipy = "^1.10.0"

[tool.poetry.dev-dependencies]
flake8 = "^6.0.0"
tox = "^4.2.1"
PySnooper = "^1.1.1"

[tool.pytest.ini_options]
testpaths = [
    "tests",
]

[tool.mypy]
mypy_path = "src"
check_untyped_defs = true
disallow_any_generics = true
ignore_missing_imports = true
no_implicit_optional = true
show_error_codes = true
strict_equality = true
warn_redundant_casts = true
warn_return_any = true
warn_unreachable = true
warn_unused_configs = true
no_implicit_reexport = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.tox]
legacy_tox_ini = """
[tox]
envlist = py37, py38, py39, py310, mypy

[gh-actions]
python =
    3.7: py37
    3.8: py38
    3.9: py39
    3.10: py310, mypy

[testenv]
"""
