[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
[project]
name = "TAInstCalorimetry"
version = "0.1.0"
authors = [
  { email="aCodingChemist@gmail.com" },
]
description = "Handling TAM Air calorimetry files made easy."
readme = "README.md"
keywords = ["calorimetry", "TAM Air", "TA Instruments", "analysis", "vizualisation"]
license = { file="LICENSE"}
requires-python = ">=3.7"